### ISSUE TITLE
Should `fftfreq` be moved to AstractFFTs.jl?

### ISSUE THREAD

**Issue by heitorPB** [JuliaDSP/DSP.jl#298] opened 2019-05-08 15:52 UTC
https://github.com/JuliaMath/AbstractFFTs.jl/issues/19 discusses about `fftfreq` missing in the AbstractFFTs package and mentions DSP.jl has it. Should this me moved to that package?

**Comment by galenlynch** [comment] 2019-05-08 16:54
The implementation or the interface?
This would include `rfftfreq`, and `Frequencies` as well, right?

**Comment by crstnbr** [comment] 2019-05-09 10:42
> The implementation or the interface?

Good question. Definitely the interface but maybe even the former. I don't see why different FFT packages would have/need different implementations.

**Comment by galenlynch** [comment] 2019-05-09 15:02
> we could also move the implementation to FFTW.jl for now

I haven't thought too much about it, but right now this seems to make the most sense to me.

I would be ok with moving `fftfreq`, `rfftfreq`, and `Frequencies` to some combination of AbstractFFTs.jl and FFTW.jl. What do other people think?

**Comment by crstnbr** [comment] 2019-05-09 15:36
> What do other people think?

Let's ask mister FFTW himself :)

@stevengj What's your opinion on this?

**Comment by stevengj** [comment] 2019-05-09 15:50
Sounds fine to me.

**Comment by ssfrr** [comment] 2019-05-09 15:51
It's not clear to me where this sort of FFT utility function should live. AFAICT generally people who are doing FFTs with regular Arrays will generally use FFTW directly (that's what I do). However, if you are using CuArrays then you wouldn't have to, because it implements its own FFT for CUDA arrays (but doesn't seem to export the fft-related functions). So I guess in that case you'd use both `AbstractFFTs` and `CuArrays`? It seems like the way to handle both use-cases would be to add the functionality to AbstractFFTs and then re-export it from `FFTW`, but that seems messy.

**Comment by stevengj** [comment] 2019-05-09 15:53
It's not much different from `fftshift`

As an aside, I don't love the name `Frequencies` … seems like it should be `FrequencyRange <: AbstractRange`

**Comment by ssfrr** [comment] 2019-05-09 15:58
yeah, definitely seems like the same situation as `fftshift`. `FFTW` just uses `@reexport` which simplifies things, so it seems like `fftfreq` and `rfftfreq` should live in `AbstractFFTs` as well.

**Comment by galenlynch** [comment] 2019-05-09 16:32
>  it's also not clear to me why you can't just use an ordinary StepRangeLen for this.

It doesn't increase monotonically:
```julia
julia> using DSP

julia> fftfreq(5)
5-element Frequencies:
  0.0
  0.2
  0.4
 -0.4
 -0.2
```

**Comment by galenlynch** [comment] 2019-05-09 16:36
It's not very much like the `AbstractRange`s that I'm used to dealing with.

**Comment by galenlynch** [comment] 2019-05-09 19:12
> seems like it should be FrequencyRange <: AbstractRange

To expand on my last comment: I don't think it's an `AbstractRange`, in the normal sense, because it's not monotonic.

**Comment by stevengj** [comment] 2019-05-09 20:04
@galenlynch, right about the monotonicity, sorry; that rules out StepRangeLen.

Conceptually, it seems like a range since it is an arra-like element defined by an arithmetic rule rather than using explicit storage, and the elements are equally spaced (albeit on a torus, i.e. with aliasing).  On the other hand, the periodicity/aliasing means that many of the `AbstractRange` methods won't work properly, so I guess that might be a problematic.

**Comment by galenlynch** [comment] 2019-05-09 21:24
It seems like its implementation is similar to a range: it does compute the value of each frequency when they are accessed, instead of storing the frequencies. It would be nice to have it work with types other than float, as per your suggestion. Is there an easy way to predict the type of a quotient? Right now, the spacing between elements is `fs/n`, where `fs` is the sampling frequency and `n` is the number of frequencies. If there is an easy way to predict what the type of `fs/n` for all types of `fs`, then it would be straight forward to make `Frequencies` more general.

**Comment by stevengj** [comment] 2019-05-09 21:46
Yes, if you do `struct Frequencies{T<:Real} <: AbstractVector{T}` with `multiplier::T` then the existing code for `fftfreq` works as-is.

**Comment by stevengj** [comment] 2019-05-09 21:50
Though I think you need `<: Number` rather than `<: Real` if you want it to work with Unitful.jl.

**Comment by hamzaelsaawy** [comment] 2019-05-09 21:53
We could replicate  [FFTViews](https://github.com/JuliaArrays/FFTViews.jl) where the FrequenceRange's indices are not `Base.OneTo` but wrap around:

```julia
julia> fs = FrequencyRange(5)
5-element Frequencies:
 -0.4
 -0.2
  0.0
  0.2
  0.4

julia> axes(fs)
 (-2:2, )
```

The issue is most people/code expects the wrap/break in the middle, and not starting with the negative frequencies

**Comment by galenlynch** [comment] 2019-05-09 22:08
But then it wouldn't be straight forward to look up the frequency of each index of a fft result.

**Comment by stevengj** [comment] 2019-05-09 22:09
I think its fine to keep the `FFTViews` approach in a separate package.

**Comment by galenlynch** [comment] 2019-05-09 22:18
How often would people want `fftfreq` with non-float spacing? I'm sympathetic to making `Frequencies`, or whatever it will be called, more general, but sometimes type parametrization can be a drag to work with. I often wish I hadn't exuberantly parametrized things when I was first learning Julia: when I use those old excessively parametrized types of mine, I find it cumbersome to compose them into new types, and to make containers for them.

**Comment by stevengj** [comment] 2019-05-10 02:29
The whole power of Julia is the ability to write type-generic code that is fast.  In a narrow application that you're not going to build anything else on top of, handling only `Float64` is fine, but this is not something you want to do in re-usable library code, especially in a package like AbstractFFTs that is intended to be a generic building block.  Besides, changing this code to a parameterized type requires a trivial two-line change.

**Comment by martinholters** [comment] 2019-05-10 10:13
I don't think I've ever used `fftfreq`, but In wonder what's the utility of wrapping around to negative frequencies? `fftfreq(5) == [0.0, 0.2, 0.4, 0.6, 0.8]` wouldn't be wrong and would potentially be simpler to handle. (OTOH, for an `fftshifted` FFT output, `[-0.4, -0.2, 0.0, 0.2, 0.4]` would clearly be desirable, and indeed `fftshift(fftfreq(5)) === -0.4:0.2:0.4`, so maybe that's the reason?)

**Comment by galenlynch** [comment] 2019-05-10 11:00
I'm definitely used to thinking of the frequencies as negative frequencies, and 0.8 would only be right in the modulo arithmetic sense, right?

**Comment by martinholters** [comment] 2019-05-10 11:21
> and 0.8 would only be right in the modulo arithmetic sense, right?

The Fourier transform of a discrete signal is periodic, so the frequencies associated to the bins calculated by the FFT are not unique. There is no single frequency which is more correct than the others modulo sampling rate, but clearly, their usefulness differs.

**Comment by stevengj** [comment] 2019-05-10 11:36
The different possible frequencies correspond to [aliasing](https://en.wikipedia.org/wiki/Aliasing), but `fftfreq` with the positive/negative frequency choice is the right choice if the discrete signals correspond to samples of a function of a continuous argument, in which case the sampling is only normally a good idea if the signal is basically [band-limited according to the Nyquist–Shannon theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem), and normally such signals are bandlimited around zero frequency.  So, if you are plotting/interpreting the Fourier components, this is normally the most useful frequencies to assign.

It is also necessary to assign frequencies if you are using the FFT to compute derivatives or perform other forms of [trigonometric interpolation](https://en.wikipedia.org/wiki/Trigonometric_interpolation).  Again, the positive/negative choice is the right choice if you have a bandlimited signal (or approximately so), and [has other nice properties](https://math.mit.edu/~stevenj/fft-deriv.pdf): it ensures that real data points will have real interpolants (modulo some careful handling of the Nyquist "middle" frequency for even N) and in some sense minimizes the mean-square slope of the interpolant.

**Comment by galenlynch** [comment] 2019-05-10 12:48
I guess I've been too focused on using FFTs for band-limited, baseband signals. Thanks for the links, and notes from your course. It'll be fun reading while my code runs today!

**Comment by crstnbr** [comment] 2019-05-11 22:37
I made a [PR over at AbstractFFTs.jl](https://github.com/JuliaMath/AbstractFFTs.jl/pull/26).

**Comment by galenlynch** [comment] 2020-01-07 18:03
Closed by JuliaMath/AbstractFFTs.jl#26 and #322.

**Closed by galenlynch** 2020-01-07 18:03 UTC
Labels: question
