### ISSUE TITLE
Error when trying to use DSP

### ISSUE THREAD

**Issue by adamnemecek** [JuliaDSP/DSP.jl#306] opened 2019-06-10 20:44 UTC
```
julia> using DSP
[ Info: Precompiling DSP [717857b8-e6f2-59f4-9121-6e50c889abd2]
WARNING: both FFTW and Util export "Frequencies"; uses of it in module Periodograms must be qualified
ERROR: LoadError: LoadError: UndefVarError: Frequencies not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/adamnemecek/.julia/dev/DSP/src/DSP.jl:3
 [6] top-level scope at none:0
 [7] include at ./boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:328 [inlined]
 [12] eval(::Expr) at ./client.jl:404
 [13] top-level scope at ./none:3
in expression starting at /Users/adamnemecek/.julia/dev/DSP/src/periodograms.jl:186
in expression starting at /Users/adamnemecek/.julia/dev/DSP/src/DSP.jl:16
ERROR: Failed to precompile DSP [717857b8-e6f2-59f4-9121-6e50c889abd2] to /Users/adamnemecek/.julia/compiled/v1.1/DSP/OtML7.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [2] _require(::Base.PkgId) at ./loading.jl:960
 [3] require(::Base.PkgId) at ./loading.jl:858
 [4] require(::Module, ::Symbol) at ./loading.jl:853
```

**Comment by galenlynch** [comment] 2019-06-10 21:59
The root cause is JuliaMath/AbstractFFTs.jl#26 taking these functions from DSP.jl and putting them in AbstractFFTs.jl instead. #300 should fix the problem but is still waiting for a response to review, and a new tagged version of AbstractFFTs.jl.

**Comment by mchitre** [comment] 2019-11-09 12:23
Struggled with this for a bit, so a quick note here of what worked:
- worked with `AbstractFFTs` `v0.4.1`
- failed with `AbstractFFTs` `v0.5.0`

**Comment by crstnbr** [comment] 2019-11-09 15:50
We should just merge #300 and everything should be back to good. Also, we should add compat entries for all dependencies so that this intermediate broken state doesn't occur the next time.

**Comment by physicalbitcoin** [comment] 2019-11-20 21:39
Greetings:
I am still getting the error, "both FFTW and Util export "Frequencies"".

I'm not sure if the above message which states "closed" refers to this error, or to the #321 issue.

Anyway, I would like to use the DSP package if it is still available. I am running Julia 1.1.1, and I have tried wiping all my .julia/compiled and .julia/packages directories prior to Pkg.add("DSP").

I would be most appreciative if you could assist me.

All the best,

pbtc

**Comment by crstnbr** [comment] 2019-11-20 22:03
@physicalbitcoin What version does `] status DSP` show? The error should be gone in v0.6.1.

**Comment by physicalbitcoin** [comment] 2019-11-20 22:07
aha! It says, "DSP v0.6.0". Not quite sure how to get the latest. Pkg.update("DSP") says "no changes".

**Comment by physicalbitcoin** [comment] 2019-11-20 22:12
I tried,
Pkg.add(PackageSpec(name="DSP",version="0.6.1")),
but this found incompatibilities with FFTW.
Maybe my julia version is lagging, or another package I have specifies a particular version of FFTW which conflicts with DSP.

**Comment by ssfrr** [comment] 2019-11-20 23:59
Maybe try with a clean environment(I.e. use `] activate /tmp/foo` and make sure you can install DSP.jl.  If that doesn’t work can you send the result of `] st -m` and maybe we can figure out what package is holding things back.

**Comment by ssfrr** [comment] 2019-11-21 00:00
Whoops, just re-read your latest message and it looks like this is resolved. I’m closing the issue, let us know if there’s still a problem.

**Closed by ssfrr** 2019-11-21 00:00 UTC

**Comment by galenlynch** [comment] 2019-11-23 13:20
Also see JuliaRegistries/General#5778
